//@version=5
indicator("Frankenstein", overlay=true)

//Inputs
emaFastLen = input.int(20, "Fast EMA")
emaSlowLen = input.int(50, "Slow EMA")
rsiLen     = input.int(14, "RSI Length")
volLen     = input.int(20, "Volume MA Length")

//Calculations
emaFast = ta.ema(close, emaFastLen)
emaSlow = ta.ema(close, emaSlowLen)
rsiVal  = ta.rsi(close, rsiLen)
volMA   = ta.sma(volume, volLen)

//Trend Conditions
// Add any type of condition in here do it for other blocks 
bullTrend = close > emaFast and emaFast > emaSlow
bearTrend = close < emaFast and emaFast < emaSlow

//Momentum Conditions
bullMomentum = rsiVal >= 45 and rsiVal <= 65
bearMomentum = rsiVal <= 55 and rsiVal >= 35

//Volume Confirmation
volConfirm = volume > volMA

//Entry Conditions
longSignal  = bullTrend and bullMomentum and volConfirm and close > open
shortSignal = bearTrend and bearMomentum and volConfirm and close < open

//Plot EMAs
plot(emaFast, color=color.orange, linewidth=2)
plot(emaSlow, color=color.blue, linewidth=2)

//Plot Signals
plotshape(longSignal, title="BUY", style=shape.triangleup,
     location=location.belowbar, color=color.green, size=size.small)

plotshape(shortSignal, title="SELL", style=shape.triangledown,
     location=location.abovebar, color=color.red, size=size.small)
